periodictable/urls.py
from django.urls import path
from . import views

app_name = 'periodictable'
urlpatterns = [
    path('',views.index, name='index'),
    path('element/<int:element_id>/', views.detail, name='detail'),
    path('setlang/<str:lang>/', views.setlang, name='setlang'),
]

pyperiodictable/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('periodictable.urls')),
    path('admin/', admin.site.urls),
]

periodictable/models.py
from django.db import models

class ChemElement(models.Model):
    atomic_number = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    symbol = models.CharField(max_length=2, unique=True)
    period = models.IntegerField(default=0)
    group = models.IntegerField(default=0)
    phase = models.CharField(max_length=100,default="")
    elem_type = models.CharField(max_length=200,default="")
    de_name = models.CharField(max_length=200,default="")
    en_name = models.CharField(max_length=200,default="")
    es_name = models.CharField(max_length=200,default="")
    fr_name = models.CharField(max_length=200,default="")
    it_name = models.CharField(max_length=200,default="")
    pt_name = models.CharField(max_length=200,default="")

periodictable/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.utils import translation
from .models import ChemElement

# Create your views here.
def index(request):
    curr_lang = translation.get_language()
    element_list = ChemElement.objects.order_by("atomic_number")
    for elem in element_list:
        elem.name = vars(elem)[curr_lang+"_name"]
    context = {
        'elements': element_list,
        'curr_lang': curr_lang,
        'type_colors': {
            'Actinide': '#e7adda',
            'Alkali Metal': '#efc355',
            'Alkaline Earth Metal': '#e8e751',
            'Halogen': '#b0dff1',
            'Lanthanide': '#a0dddd',
            'Metal': '#a3cbd2',
            'Metalloid': '#7ac8b9',
            'Noble Gas': '#c0ffff',
            'Nonmetal': '#a5dc5c',
            'Transactinide': '#f19dac',
            'Transition Metal': '#f19dac',
        },
    }
    return  render(request,'periodictable/index.html',context) 

def detail(request, element_id):
    curr_lang = translation.get_language()
    element = ChemElement.objects.get(atomic_number=element_id)
    element.name = vars(element)[curr_lang+"_name"]
    context = {
        'element': element,
        'type_colors': {
            'Actinide': '#e7adda',
            'Alkali Metal': '#efc355',
            'Alkaline Earth Metal': '#e8e751',
            'Halogen': '#b0dff1',
            'Lanthanide': '#a0dddd',
            'Metal': '#a3cbd2',
            'Metalloid': '#7ac8b9',
            'Noble Gas': '#c0ffff',
            'Nonmetal': '#a5dc5c',
            'Transactinide': '#f19dac',
            'Transition Metal': '#f19dac',
        },
    }
    return render(request,'periodictable/detail.html',context) 

def setlang(request, lang):
    user_language = lang
    translation.activate(user_language)
    response = redirect(request.META.get('HTTP_REFERER'))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, user_language)
    return response

periodictable/templates/periodictable/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-extension.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">

    <title>{% translate "periodic_table_title" %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar fixed-top text-light bg-dark">  
        <span class="navbar-brand" ">{% translate "periodic_table_title" %}</span>
        <!-- Example split danger button -->
        <div class="btn-group">
          <button type="button" class="btn btn-secondary">{% translate "display_language"%}</button>
          <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="/setlang/de/"><img src="{% static 'imgs/de.png' %}"> {% translate "de_language" %}</a>
            <a class="dropdown-item" href="/setlang/en/"><img src="{% static 'imgs/gb.png' %}"> {% translate "en_language" %}</a>
            <a class="dropdown-item" href="/setlang/es/"><img src="{% static 'imgs/es.png' %}"> {% translate "es_language" %}</a>
            <a class="dropdown-item" href="/setlang/fr/"><img src="{% static 'imgs/fr.png' %}"> {% translate "fr_language" %}</a>
            <a class="dropdown-item" href="/setlang/it/"><img src="{% static 'imgs/it.png' %}"> {% translate "it_language" %}</a>
            <a class="dropdown-item" href="/setlang/pt/"><img src="{% static 'imgs/br.png' %}"> {% translate "pt_language" %}</a>
          </div>
        </div>
      </nav>   
    </div><!--navbar-->
    <div class="content container ml-0 container-fluid">
        <br><br><br>
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div> <!--col-md-8-->
        </div><!--row-->
      </div> <!--content container-->
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

periodictable/templates/periodictable/detail.html
{% extends 'periodictable/base.html' %}
{% load dicthash %}
{% load i18n %}

{% block content %}
    <table class="table table-borderless" style="width: 5rem; background-color: {{ type_colors|hash:element.elem_type }};">
      <tbody>
        <tr>
          <td>
            <h3>{{ element.atomic_number }}</h3>
            <h1>{{ element.symbol }}</h1>
            <h4>{{ element.name }}</h2>  
          </td>
        </tr>
      </tbody>
    </table>
    
    <table class="table table-borderless">
      <tbody>
          <tr>
            <td><b>{% translate "label_atomic_number" %}</b></td>
            <td>{{ element.atomic_number }}</td>
          </tr>
          <tr>
            <td><b>{% translate "label_period" %}</b></td>
            <td>{{ element.period }}</td>
          </tr>
          <tr>
            <td><b>{% translate "label_group" %}</b></td>
            <td>{{ element.group }}</td>
          </tr>
          <tr>
            <td><b>{% translate "label_phase" %}</b></td>
            <td>{{ element.phase }}</td>
          </tr>
          <tr>
            <td><b>{% translate "label_type" %}</b></td>
            <td>{{ element.elem_type }}</td>
          </tr>
      </tbody>
    </table>

    <a href="{% url 'periodictable:index' %}" class="btn btn-primary">{% translate "go_back" %}</a>
{% endblock %}

periodictable/templates/periodictable/index.html
{% extends 'periodictable/base.html' %}
{% load static %}
{% load dicthash %}
{% load i18n %}

{% block content %}
<table class="table table-borderless">
  <tbody>
      {% for element in elements %}
        {% if element.group == 1 %}
        <tr style="line-height: 0.5rem; min-height: 0.5rem; height: 0.5rem;">
        {% endif %}
        {% if element.period >= 6 and element.period <= 7 %}
          {% if element.atomic_number >= 57 and element.atomic_number <= 71 or element.atomic_number >= 89 and element.atomic_number <= 103 %}
            {% if element.atomic_number == 57 %}
            <td style="width: 5.55%; margin: 0;">
              <img src="{% static 'icons/arrow-down-square.svg' %}" alt="" width="32" height="32" title="Bootstrap">
            </td>
            {% endif %}
            {% if element.atomic_number == 89 %}
            <td style="width: 5.55%; margin: 0;">
              <img src="{% static 'icons/arrow-down-square-fill.svg' %}" alt="" width="32" height="32" title="Bootstrap">
            </td>
            {% endif %}
          {% else %}
            <td class="ml-0 mt-0 mr-0 mb-0 border border-dark" style="width: 5.55%; background-color: {{ type_colors|hash:element.elem_type }};">
              <small style="font-size: 0.9rem;">{{ element.atomic_number }}</small>
              <h4><a href="{% url 'periodictable:detail' element.atomic_number %}">{{ element.symbol }}</a></h4> 
              <p class="element_name" lang="{{ curr_lang }}">{{ element.name }}</p>
            </td>
          {% endif %}
        {% else %}
          <td class="ml-0 mt-0 mr-0 mb-0 border border-dark" style="width: 5.55%; background-color: {{ type_colors|hash:element.elem_type }};">
            <small style="font-size: 0.9rem;">{{ element.atomic_number }}</small>
            <h4><a href="{% url 'periodictable:detail' element.atomic_number %}">{{ element.symbol }}</a></h4> 
            <p class="element_name" lang="{{ curr_lang }}">{{ element.name }}</p>
          </td>
        {% endif %}
        {% if element.period == 1 and element.group == 1%}
          {% with ''|center:16 as range %}
            {% for _ in range %}
            <td>
            </td>
            {% endfor %}
          {% endwith %}
        {% endif %}
        {% if element.period >= 2 and element.period <= 3 and element.group == 2%}
          {% with ''|center:10 as range %}
            {% for _ in range %}
            <td>
            </td>
            {% endfor %}
          {% endwith %}
        {% endif %}
        {% if element.group == 18 %}
        </tr>
        {% endif %}
      {% endfor %} 
      <tr><td><br></td></tr>
      {% for element in elements %}
        {% if element.period == 6 or element.period == 7 %}
          {% if element.group == 1 %}
            <tr style="line-height: 0.5rem; min-height: 0.5rem; height: 0.5rem;">
          {% endif %}
          {% if element.atomic_number == 57 %}
          <td style="width: 5.55%; margin: 0;">
            <img src="{% static 'icons/arrow-right-square.svg' %}" alt="" width="32" height="32" title="Bootstrap">
          </td>
          {% endif %}
          {% if element.atomic_number == 89 %}
          <td style="width: 5.55%; margin: 0;">
            <img src="{% static 'icons/arrow-right-square-fill.svg' %}" alt="" width="32" height="32" title="Bootstrap">
          </td>
          {% endif %}

          {% if element.atomic_number >= 57 and element.atomic_number <= 71 or element.atomic_number >= 89 and element.atomic_number <= 103 %}
            <td class="ml-0 mt-0 mr-0 mb-0 border border-dark" style="width: 5.55%; background-color: {{ type_colors|hash:element.elem_type }};">
              <small style="font-size: 0.9rem;">{{ element.atomic_number }}</small>
              <h4><a href="{% url 'periodictable:detail' element.atomic_number %}">{{ element.symbol }}</a></h4> 
              <p class="element_name" lang="{{ curr_lang }}">{{ element.name }}</p>
            </td>
          {% else %}
            <td>
            </td>
          {% endif %}
          {% if element.group == 18 %}
          </tr>
          {% endif %}
        {% endif %}
      {% endfor %} 
  </tbody>
</table>
{% endblock %}